version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn test
  build:
    commands:
      - yarn build

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - node_modules/**/*
